version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    network_mode: host
    depends_on:
      - mongo
      - qdrant
      - go-service

  go-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: go-service
    network_mode: host
    depends_on:
      - mongo
      - qdrant

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sliit123
    network_mode: host

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: sliit123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: sliit123
    network_mode: host

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./.qdrant_storage:/qdrant/storage:z
    network_mode: host
